# Generated by Django 4.2.1 on 2023-05-23 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeaccount', models.CharField(max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.company')),
            ],
        ),
        migrations.CreateModel(
            name='Sintetic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sintetic', models.CharField(max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.company')),
                ('typeaccount', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.typeaccount')),
            ],
        ),
        migrations.CreateModel(
            name='Analitic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analitic', models.CharField(max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.company')),
                ('sintetic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.sintetic')),
            ],
        ),
    ]
