# Generated by Django 4.2.1 on 2023-05-24 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
        ('users', '0005_alter_company_company_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.company')),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='criado em ')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modificado em ')),
                ('date', models.DateField()),
                ('n_doc', models.CharField(blank=True, max_length=10, null=True)),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('obs', models.CharField(blank=True, max_length=100, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.company')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='entrys.document_type')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='EntryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typemovement', models.CharField(choices=[('d', 'debito'), ('c', 'credito')], max_length=1)),
                ('value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('Validation', models.DecimalField(decimal_places=2, max_digits=15)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.analitic')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrys.entry')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
    ]
