# Generated by Django 4.2.1 on 2023-05-24 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrys', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document_type',
            options={'ordering': ('document_type',)},
        ),
    ]
