# Generated by Django 4.2.1 on 2023-05-25 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrys', '0003_alter_entryitem_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='n_doc',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
