# Generated by Django 4.2.1 on 2023-05-26 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrys', '0004_alter_entry_n_doc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entryitem',
            name='Validation',
        ),
        migrations.AddField(
            model_name='entryitem',
            name='validation',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
