# Generated by Django 4.2.1 on 2023-05-26 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_company_company_name'),
        ('entrys', '0005_remove_entryitem_validation_entryitem_validation'),
    ]

    operations = [
        migrations.AddField(
            model_name='entryitem',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='users.company'),
            preserve_default=False,
        ),
    ]
