# Generated by Django 4.2.1 on 2023-05-28 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrys', '0008_alter_entry_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entryitem',
            name='validation',
        ),
    ]
