# Generated by Django 4.2.1 on 2023-05-30 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrys', '0009_remove_entryitem_validation'),
    ]

    operations = [
        migrations.AddField(
            model_name='entryitem',
            name='value_ref',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=15),
            preserve_default=False,
        ),
    ]
