# Generated by Django 4.2.1 on 2023-05-30 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrys', '0010_entryitem_value_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='entryitem',
            name='DELETE',
            field=models.BooleanField(default=False),
        ),
    ]
