# Generated by Django 4.2.1 on 2023-05-30 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrys', '0011_entryitem_delete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entryitem',
            name='DELETE',
        ),
    ]
