# Generated by Django 4.2.1 on 2023-05-30 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrys', '0012_remove_entryitem_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='credit',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entry',
            name='debit',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=15),
            preserve_default=False,
        ),
    ]
