# Generated by Django 4.2.1 on 2023-05-31 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrys', '0015_remove_entryitem_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='n_doc',
            field=models.CharField(max_length=20),
        ),
    ]
