# Generated by Django 4.2.1 on 2023-05-31 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrys', '0016_alter_entry_n_doc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='description',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='entry',
            name='obs',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
