# Generated by Django 4.2.1 on 2023-07-18 17:25

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0005_alter_company_company_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='criado em ')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modificado em ')),
                ('typeperson', models.CharField(choices=[('pf', 'pessoa fisica'), ('pj', 'pessoa juridica')], max_length=2)),
                ('name', models.CharField(max_length=60)),
                ('nickname', models.CharField(blank=True, max_length=60, null=True)),
                ('cpf_cnpj', models.CharField(blank=True, max_length=20, null=True)),
                ('rg_ie', models.CharField(blank=True, max_length=20, null=True)),
                ('anniversary_fundationdate', models.DateField(blank=True, null=True)),
                ('cep', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=60, null=True)),
                ('city', models.CharField(blank=True, max_length=20, null=True)),
                ('uf', models.CharField(blank=True, max_length=2, null=True)),
                ('country', models.CharField(blank=True, max_length=20, null=True)),
                ('obs', models.CharField(blank=True, max_length=60, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='PersonSeller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission', models.DecimalField(decimal_places=0, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('sellerobs', models.CharField(blank=True, max_length=60, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persons.person')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='PersonCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_discount', models.DecimalField(decimal_places=0, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('payment_term', models.DecimalField(decimal_places=0, max_digits=3)),
                ('customerobs', models.CharField(blank=True, max_length=60, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persons.person')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='PersonContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typecontact', models.CharField(choices=[('c', 'celular'), ('e', 'e-mail'), ('t', 'telefone')], max_length=1)),
                ('contactdescription', models.CharField(blank=True, max_length=60, null=True)),
                ('contactobs', models.CharField(blank=True, max_length=60, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persons.person')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
    ]
